name: Taiwan Sentinel-2 Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # 每週運行一次（週一）
  workflow_dispatch:  # 允許手動觸發

jobs:
  run-taiwan-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install planetary-computer pystac-client rasterio folium matplotlib

      - name: Run Taiwan Analysis Script
        run: python taiwan_analysis.py

      - name: Upload Taiwan Image
        uses: actions/upload-artifact@v4
        with:
          name: taiwan-image
          path: taiwan_image.tif
